
server:
  port: 7001

spring:
  application:
    name: "Customer-Service"
  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    leaseExpirationDurationInSeconds: 2
